src/main/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('update_filters/', views.update_filters, name='update_filters'),
    path('', views.main, name='main'),
    path('call', views.callView, name='callView')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/models.py
from django.db import models
from django import forms


class CommonSettings(models.Model):
    """Model for settings"""

    class Meta:
        verbose_name_plural = 'common settings'

    phone_number = models.CharField(max_length=20, blank=True)
    yandex_counter = models.CharField(max_length=10000, blank=True)
    mail = models.EmailField(max_length=50, blank=True)


class Products(models.Model):
    class Meta:
        verbose_name_plural = 'products'

    name = models.CharField(max_length=1000, blank=True)
    price = models.CharField(max_length=1000, default=1000)
    text = models.CharField(max_length=20000)

    def __str__(self):
        return self.name


class Filters(models.Model):
    class Meta:
        verbose_name_plural = 'filters'

    product = models.ManyToManyField(Products, related_name='product_filters', blank=True)
    filter_name = models.CharField(max_length=100)

    def __str__(self):
        return self.filter_name


class Images(models.Model):
    class Meta:
        verbose_name_plural = 'images'

    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.product.name


class SaleAside(models.Model):
    class Meta:
        verbose_name_plural = 'sale_aside'

    name = models.CharField(max_length=1000, blank=True)
    image = models.ImageField(upload_to='sale_aside')
    check = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class SaleMain(models.Model):
    class Meta:
        verbose_name_plural = 'sale_main'

    name = models.CharField(max_length=1000, blank=True)
    image = models.ImageField(upload_to='sale_main')
    check = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class CallForm(forms.Form):
    name = forms.CharField()
    phone = forms.CharField()
    address = forms.CharField()

src/app/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from itertools import chain
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse, BadHeaderError, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from app.models import CommonSettings, Filters, Products, Images, CallForm, SaleAside, SaleMain
from django.template import loader
from django.template import Context, Template

from main import settings


@csrf_exempt
def main(request):
    """Render home page"""
    try:
        yandex_counter = CommonSettings.objects.all()[0].yandex_counter
        phone_number = CommonSettings.objects.all()[0].phone_number
        mail = CommonSettings.objects.all()[0].mail
    except:
        yandex_counter, phone_number, mail = '', '', ''
    product_new = []
    filters_names = Filters.objects.all()
    products = Products.objects.all()
    saleaside = SaleAside.objects.filter(check=True)
    salemain = SaleMain.objects.filter(check=True)
    params = {
        'yandex_counter': yandex_counter,
        'phone_number': phone_number,
        'mail': mail,
        'filters_names': filters_names,
        'products': products,
        'saleaside': saleaside,
        'salemain': salemain,
    }
    return render(request, 'app/index.html', params)


@csrf_exempt
def update_filters(request):
    ids_ = request.POST.get('ids_').split(',')
    salemain = SaleMain.objects.filter(check=True)
    if not ids_[0]:
        res = Filters.objects.all()
        new_qs = Products.objects.none()
        products = Products.objects.all()
        for i in res:
            new_qs = list(chain(new_qs, i.product.all()))
        params = {'products': products,
                  'salemain': salemain,
                  }
    else:
        res = Filters.objects.filter(id__in=ids_)
        new_qs = Products.objects.none()
        for i in res:
            new_qs = list(chain(new_qs, i.product.all()))
        params = {'products': new_qs,
                  'salemain': salemain,
                  }
    # return HttpResponse(params)

    html = render_to_string('app/products.html', params)
    return HttpResponse(html)

    # t = loader.get_template('app/products.html')
    # return HttpResponse(t.render(params, request))


EMAIL_TO = ['2408199898@mail.ru']


@csrf_exempt
def callView(request):
    # Если форма заполнена корректно, сохраняем все введённые пользователем значения
    if request.method == 'POST':
        form = CallForm(request.POST)
        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            address = form.cleaned_data['address']

            try:
                message = 'Телефон: ' + phone + '   Имя: ' + name + '   Адресс: ' + address
                send_mail('Просьба перезвонить', message, settings.EMAIL_HOST_USER, EMAIL_TO)
            except BadHeaderError:  # Защита от уязвимости
                return HttpResponse('Invalid header found')
        else:
            # Заполняем форму
            form = CallForm()
    # Отправляем форму на страницу
    return HttpResponseRedirect("/")

src/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Удалить -->
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="Pragma" content="no-cache" />
    <meta name="yandex-verification" content="7069ee2afd6847fb" />
    <!-- Удалить -->
    <title>Каталог жалюзи и штор</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap&subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/screen.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/card.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/sweet-alert.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/galery.css' %}"> {{ yandex_counter|safe }}
    <link rel="stylesheet" href="{% static 'app/css/normalize-5.0.0.css' %}">


    <script type="text/javascript" src="{% static 'app/js/jquery-3.3.1.min.js' %}"></script>
</head>

<body onload="init()">
    <div class="grid">
        <header class="main__header">
            <div class="main__contact logo">
                <img src="{% static 'app/img/logo.svg' %}" height="50" alt="logo">
                <h1 class="main__caption">Каталог жалюзи и штор</h1>
            </div>
            <a class="call_free gradient trigger">Вызвать замерщика БЕСПЛАТНО</a>
            <div class="modal-wrapper">
              <div class="modal">
                <div class="head">
                    <h5>Заказать замерщика</h5>
                </div>
                <div class="content">
                    <div class="text">
                        Заполните форму, и мы перезвоним Вам в ближайшее рабочее время, как только получим это сообщение.
                    </div>
                    <form id="contactForm" action="" method="POST" class="contact-form">
                        {% csrf_token %}
                        <div class="name">
                            <label for="name">Как к Вам обращаться?</label>
                            <input name="name" type="text" class="form-control" id="name" placeholder=" Имя   " required>
                        </div>
                        <div class="phone">
                            <label for="phone">Телефон</label>
                            <input name="phone" type="tel" class="form-control" id="phone" placeholder=" +7(   )  " required>
                        </div>
                        <div class="address">
                            <label for="address">Адрес</label>
                            <input name="address" type="text" class="form-control" id="address" placeholder=" Адрес   " required>
                        </div>
                        <div class="politics">
                            <label for="politics"></label>
                            <input type="checkbox" id="politics">
                            <p>Даю согласие на обработку моих персональных данных, согласно Политике конфедициальности</p>
                        </div>
                        <input type="submit" class="gradient no_disabled" value="Отправить" id="callForm"  disabled>
                    </form>
                </div>
              </div>
            </div>
            <div class="main__contact call">
                <img src="{% static 'app/img/smartphone.svg' %}" height="19" alt="phone">
                <div class="wrapper">
                    <span>Сделать заказ</span>
                    <a href="">{{ phone_number }}</a>
                </div>
            </div>
        </header>
        <aside class="sidebar" id="sidebar">
            <div class="sidebar__overlay"></div>
            <header class="sidebar__header">
                <button class="sidebar__btn_mobile" id="sidebar__btn_mobile">
                    <i>&#9776;</i>
                </button>
                <button class="sidebar__btn" id="sidebar__btn"><i>&#9776;</i>
                    <h3 class="sidebar__caption">Фильтры</h3></button>
            </header>
            <ul class="sidebar__list">
                {% for filter_name in filters_names %}
                <li data-id="{{ filter_name.id }}" class="update_filters">
                    <label>
                        <input type="checkbox">
                        <span>{{filter_name.filter_name}}</span>
                    </label>
                </li>
                {% endfor %}
            </ul>
            <div id="viewport1">
                <div class="saleaside" id="box1">
                    {% for img in saleaside %}
                        {% if img != None %}
                            {% if forloop.counter0 == 0 %}
                                <figure class="slide jbs-current" data-proportion-h="1.5">
                            {% else %}
                                <figure class="slide" data-proportion-h="1.5">
                            {% endif %}
                                    <img src="media/{{img.image}}" onerror="main_img_none()" alt="sale_luming">
                                </figure>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </aside>
        <main class="main" id="main">
            <div class="main__content">

                {% include "app/products.html" %}

            </div>
        </main>
    </div>

    <section class="galery" id="galery">
        <div class="overlay"></div>
        <div class="content">
            <div class="controls">
                <button class="last control" id="galery__last_btn">&#8249;</button>
                <button class="next control" id="galery__next_btn">&#8250;</button>
            </div>
            <div class="photos"></div>
        </div>
    </section>

    <script type="text/javascript" src="{% static 'app/js/hammer.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/sweet-alert.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/inputmask.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/jquery.inputmask.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/box-slider-all.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/stickjaw.min.js' %}"></script>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var $images = $('.saleaside img');
            var imagesLeftToLoad = $images.length;
            $images.on('load', function () {
              imagesLeftToLoad -= 1;
                init();
            });

            var init = function () {
              var $box = $('.saleaside')
                , slideInterval = 5000
                , defaultOptions = {
                      speed: 800
                    , autoScroll: true
                    , timeout: slideInterval
                    , effect: 'blindLeft'
                    , blindCount: 6
                  }
                , effectOptions = {
                    'blindLeft': {blindCount: 15}
                  , 'blindDown': {blindCount: 15}
                  , 'tile3d': {tileRows: 6, rowOffset: 80}
                  , 'tile': {tileRows: 6, rowOffset: 80}
                };

              // initialize the plugin with the desired settings
              $box.boxSlider(defaultOptions);
            };
            return false;
		  });

        var SJ_init = {
            options: {
                hlw: true,
                wlh: true,
                hlt: true,
                wlt: true,
                alo: true,
                ohlt: true,
                owlt: true
            },
            settings: {
                windowResize: true,
                writeHystory: true
            }
        };

        var e = new SJ(SJ_init);

        function aside_img_none() {
            $(this).hide();
        }

        $(function () {
            $('.modal #phone').inputmask({
                mask: "+7(XXX)XXX-XX-XX",
                definitions: {
                    'X': {
                        validator: "[0-9]",
                    }
                }
            });
        });

        let submit = document.getElementById('callForm');
        document.getElementById('politics').onclick = function (qualifiedName, value) {
            if (this.checked) {
                submit.removeAttribute('disabled');
                submit.classList.remove('no_disabled');
            } else {
                submit.setAttribute('disabled', value);
                submit.classList.add('no_disabled');
            }
        };

        submit.onclick = function() {
            let dataValid = true;

            $('.modal').find('.form-control').each(function (index, value) {
                let self = $(this);
                if (self.val() === '') {
                    self.addClass('empty_field');
                    setTimeout(function () {
                        self.removeClass('empty_field');
                    }, 800);
                    dataValid = false;
                } else {
                    self.removeClass('empty_field');
                }
            });
            if (dataValid === true) {
                sendAjaxFormC('result_form', 'contactForm', 'call');
                return false;
            }
        };

        function sendAjaxFormC(result_form, ajax_form, url) {
            $.ajax({
                url:     url, //url страницы ()
                type:     'POST', //метод отправки
                dataType: 'html', //формат данных
                data: $("#"+ajax_form).serialize(),  // Сеарилизуем объект
                success: function(response) { //Данные отправлены успешно
                    swal({
                        title: "Ура!",
                        text: "Ваша просьба перезвонить отправлена!",
                        type: "success",
                        confirmButtonText: "Закрыть"
                    });
                    $('#contactForm').find('input[type=text], textarea').val('');
                    $('#contactForm').find('input[type=checkbox]').prop('checked', false);
                },
                error: function(response) { // Данные не отправлены
                    swal({
                        title: "Что-то пошло не так!",
                        text: "Попробуйте еще раз",
                        type: "error",
                        confirmButtonText: "Закрыть"
                    });
                }
            });
        }

        $( document ).ready(function () {
          $('.trigger').on('click', function() {
             $('.modal-wrapper').toggleClass('open');
             return false;
          });
        });
        $(document).click(function (e) {
            if ($(e.target).is('.modal-wrapper')) {
                $('.modal-wrapper').removeClass('open');
            }
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('li').on('click', function(e) {
            e.stopPropagation();
            e.preventDefault();
            $(this).toggleClass('active');

            let ids = $('li.active').map(function() {
                return $(this).attr("data-id");
            }).get().join(',');;

            let data = {
                'ids_': ids,
                'csrfmiddlewaretoken': getCookie('csrftoken')
            };

            $.ajax({
                url: '/update_filters/',
                method: 'POST',
                data: data,
                success: function (data) {
                    // $('.main__content').load('app/products.html');
                    $('.main__content').html(data);
                    init();
                },
                error: function (d) {
                }
            });
        });

    </script>

</body>

</html>

src/app/templates/app/products.html
{% for product in products%}
    {% if forloop.counter0 == 3 and forloop.counter0 != 0 %}
        <div id="viewport">
            <div class="salemain" id="box">
                {% for img in salemain %}
                    {% if img != None %}
                        {% if forloop.counter0 == 0 %}
                            <figure class="slide jbs-current" data-proportion-h="0.32">
                        {% else %}
                            <figure class="slide" data-proportion-h="0.32">
                        {% endif %}
                                <img src="media/{{img.image}}" onerror="main_img_none()" alt="sale_luming">
                            </figure>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
        <div class="main__card card">
            <div class="card__images">
                {% for k in product.images_set.all %}
                    {% if forloop.counter < 5 %}
                        <img src='media/{{k.image}}' alt="">
                    {% endif %}
                {% endfor %}
                <footer class="card__footer">
                    <div class="card__control"></div>
                </footer>
            </div>
            <div class="card__text">
                <header class="card__header">
                    <h4 class="card__title">{{product.name}}</h4>
                </header>
                <div class="card__product__text">
                    {{product.text}}
                </div>
                <footer class="card__footer">
                    <span class="card__price">
                      <i>{{product.price}}<small>&#8381;</small> </i>за м<sup>2</sup>
                    </span>
                    <a class="card__btn gradient trigger_more_photo" onclick="more_photo_open({{product.id}})">
                        больше фото
                    </a>
                </footer>
            </div>
        </div>
    <div class="modal-wrapper_more_photo {{product.id}}">
      <div class="modal">
        <div class="content">
            <div class="head">
                <h5>все фото</h5>
            </div>
            <div class="card__images">
                {% for z in product.images_set.all %}
                    <img src='media/{{z.image}}' alt="">
                {% endfor %}
                <a class="last {{product.id}} control" id="galery__last_btn">&#8249;</a>
                <a class="next {{product.id}} control" id="galery__next_btn">&#8250;</a>
                <footer class="card__footer">
                    <div class="card__control"></div>
                </footer>
            </div>
        </div>
      </div>
    </div>
{% endfor %}
<script>
function load_sale() {
    var $images = $('#box .slide > img');
    var imagesLeftToLoad = $images.length;
    $images.on('load', function () {
      imagesLeftToLoad -= 1;

      if (imagesLeftToLoad === 0) {
        init();
      }
    });

    var init = function () {

      var $box = $('#box')
        , slideInterval = 5000
        , defaultOptions = {
              speed: 1200
            , autoScroll: true
            , timeout: slideInterval
            , effect: 'blindDown'
            , responsive: true
          }
        , effectOptions = {
            'blindLeft': {blindCount: 15}
          , 'blindDown': {blindCount: 15}
          , 'tile3d': {tileRows: 6, rowOffset: 80}
          , 'tile': {tileRows: 6, rowOffset: 80}
        };

      // initialize the plugin with the desired settings
      $box.boxSlider(defaultOptions);

        var SJ_init = {
            options: {
                hlw: true,
                wlh: true,
                hlt: true,
                wlt: true,
                alo: true,
                ohlt: true,
                owlt: true
            },
            settings: {
                windowResize: true,
                writeHystory: true
            }
        };

        var e = new SJ(SJ_init);
    };
}



function main_img_none() {
    $('.salemain img').hide();
}

document.addEventListener('DOMContentLoaded' ,function () {
    load_sale();
    const len = document.querySelectorAll('.main__content .main__card');
    len.forEach((x) => {
        if (x.querySelectorAll('img').length === 0) {
            x.style.display = 'none';
        }
    })
});

function more_photo_open(k) {
    $('.modal-wrapper_more_photo.' + k).addClass('open');
    const cards = document.querySelectorAll('.main__content .modal .content');
    cards.forEach((card) => {
        if (card !== undefined) {
            const photoQuantity = card.querySelectorAll('.card__images img').length;
            if (photoQuantity !== 0) {
                const cardControl = card.querySelector('.card__control');

                if (card.querySelector('.card__control div') === null) {
                    const cardPhotos = card.querySelectorAll('.card__images img');
                    const cardPhotosContainer = card.querySelector('.card__images');

                    for (let i = 0; i < photoQuantity; i++) {
                        cardControl.innerHTML += `<div data-index="${i}"></div>`;
                        cardPhotos[i].setAttribute('data-index', i);
                        if (i === 0) {
                            cardControl.querySelector('div[data-index="0"]').classList.add('active');
                        }
                    }

                    // cardControl.firstChild.classList.add('active'); # подсвечивает кружок зеленым

                    const cardControlContainer = document.createElement('div');
                    cardControlContainer.classList.add('card__control_container');
                    cardPhotosContainer.append(cardControlContainer);

                    for (let i = 0; i < photoQuantity; i++) {
                        cardControlContainer.innerHTML += `
                    <div style="width: ${100 / photoQuantity}%" class="card__photo_control" data-index="${i}"></div>`;
                    }

                    const cardControls = card.querySelectorAll('.card__control div');
                    let index = 0;
                    cardControls.forEach((control) => {
                        control.addEventListener('mouseover', (e) => {
                            index = control.dataset.index;

                            cardPhotos.forEach((photo) => {
                                photo.style.left = `calc(-100% * ${index})`;
                            });

                            cardControls.forEach((control) => {
                                control.classList.remove('active');
                            });
                            control.classList.add('active');
                        });
                    });

                    $('.next').click(function (e) {
                        const cardPhotos = card.querySelectorAll('.card__images img');
                        const photos = card.querySelector('.card__images');
                        const cardControl = card.querySelector('div.active');
                        let i = cardControl.getAttribute('data-index');
                        if (i < cardPhotos.length - 1) {
                            i++;
                            cardPhotos.forEach((photo) => {
                                photo.style.left = `calc(-100% * ${i})`;
                            });
                            let last_index = i - 1;
                            photos.querySelector('div[data-index="' + last_index + '"]').classList.remove('active');
                            photos.querySelector('div[data-index="' + i + '"]').classList.add('active');
                        } else {
                            i = 0;
                            cardPhotos.forEach((photo) => {
                                photo.style.left = `calc(-100% * ${i})`;
                            });

                            let last_index = cardPhotos.length - 1;
                            photos.querySelector('div[data-index="' + last_index + '"]').classList.remove('active');
                            photos.querySelector('div[data-index="' + i + '"]').classList.add('active');
                        }
                    });

                    $('.last').click(function (e) {
                        const cardPhotos = card.querySelectorAll('.card__images img');
                        const photos = card.querySelector('.card__images');
                        const cardControl = card.querySelector('.card__control div.active');
                        let i = cardControl.getAttribute('data-index');
                        if (i > 0) {
                            i--;
                            cardPhotos.forEach((photo) => {
                                photo.style.left = `calc(-100% * ${i})`;
                            });
                            let next_index = i + 1;
                            photos.querySelector('div[data-index="' + next_index + '"]').classList.remove('active');
                            photos.querySelector('div[data-index="' + i + '"]').classList.add('active');
                        } else {
                            i = cardPhotos.length - 1;
                            cardPhotos.forEach((photo) => {
                                photo.style.left = `calc(-100% * ${i})`;
                            });

                            let next_index = cardPhotos.length - 1;
                            photos.querySelector('div[data-index="' + 0 + '"]').classList.remove('active');
                            photos.querySelector('div[data-index="' + next_index + '"]').classList.add('active');
                        }
                    });
                }
            }
        }

    })
}

$(document).click(function(e) {
    if ($(e.target).is('.modal-wrapper_more_photo')) {
        $('.modal-wrapper_more_photo').removeClass('open');
    }
});

</script>